### ISSUE TITLE
When will ExCore release?

### ISSUE THREAD

**Issue by HPLQAQ** [Asthestarsfalll/ExCore#35]
I'm currenting building a deeplearning benchmark for a specific task, and is looking for a better config managment tool instead of yacs. I like the design of ExCore, are there any release plans?

**Comment by Asthestarsfalll** [comment]
Hi, thanks for your attention. The latest version `0.1.1beta` of ExCore has been released on pypi. You can use `pip install excore==0.1.1b0` to install ExCore. **Note: do not use 0.1.1.**
There is still a long way for ExCore,  I have some ideas to enhance it but don't have too much time. If it's helpful to you, I hope your can give some feedbacks to make ExCore more easy-to-use.
Feel free to share the link to your benchmark. If ExCore undergoes any breaking changes or introduces new features , I can help you to update the code.

**Comment by Asthestarsfalll** [comment]
You can add my wechat `Asthestarsfell`

**Comment by HPLQAQ** [comment]
Thanks very much! Sorry for the late reply.
I've added your wechat.
